###
GET http://localhost:5000/users
###
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Raihannur",
  "email": "rehanur@gmail.com",
  "password": "adine123fawas",
  "confPassword": "adine123fawas",
  "role": "user"
}
###
GET http://localhost:5000/users/eece6918-dc64-4c26-9875-5ec2fe3fdc8c
###
patch http://localhost:5000/users/60eba823-5066-4e05-b1bd-84e63d9499c9
Content-Type: application/json

{
  "name": "Muhammad Habib",
  "email": "madani@gmail.com",
  "password": "88881111",
  "confPassword": "88881111",
  "role": "user"
}
###
DELETE  http://localhost:5000/users/4aa0e4d9-1ccd-4322-9071-176c71d33f08


###
# user
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "rehanur@gmail.com",
  "password": "adine123fawas"
}

###
# admin
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "12345678"
}

###
GET http://localhost:5000/me
###
DELETE  http://localhost:5000/logout

###
GET http://localhost:5000/products

###
GET http://localhost:5000/products/6452c56f-6c88-433f-97a0-87d2b6e381bc

###
DELETE http://localhost:5000/products/6452c56f-6c88-433f-97a0-87d2b6e381bc